apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: LoadBalancer
  creationTimestamp: null
  labels:
    io.kompose.service: hello-go-tcp
  name: hello-go-tcp
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app: hello-go
  type: LoadBalancer
status:
  loadBalancer: {}
