apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: hello-go-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
      #     volumeMounts:
      #       - name: example-volume
      #         mountPath: /opt/app/file_to_mount.txt
      # volumes:
      #   - name: example-volume
      #     hostPath:
      #       path: /Users/zhi.q@nylas.com/KomposePlayground/file_to_mount.txt
      #       type: File