apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-master
    spec:
      containers:
        - image: k8s.gcr.io/redis:e2e
          name: redis-master
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
