apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: LoadBalancer
  creationTimestamp: null
  labels:
    app: pub-sub-emulator
  name: pub-sub-emulator
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    app: pub-sub-emulator
  type: LoadBalancer
status:
  loadBalancer: {}
